### ISSUE TITLE
configure github sponsors

### ISSUE THREAD

**Issue by seanjensengrey** [vEnhance/napkin#89] opened 2020-07-04 15:17 UTC
What a phenomenal project and artifact! 

Please consider setting up [github sponsors](https://github.blog/2020-03-24-getting-started-with-github-sponsors/) so that you can receive funds from any github user who already has payment information on file. Github takes no cut.

Once configured there will be a sponsor button in the upper right , you can see it in action on the [Intellij Elixir Plugin](https://github.com/KronicDeth/intellij-elixir) page.

And thanks for using the GPL so that it can be extended and remixed.

**Comment by vEnhance** [comment] 2020-08-05 05:07
Sorry it's taking me so long to circle back to this (I spent all of July running a certain summer camp). Since #91 was created, I'm going to close this as a duplicate of that issue.

**Closed by vEnhance** 2020-08-05 05:07 UTC
